### PR TITLE
Don't hide hang up button when showing dialpad (#9)

### LINKED ISSUE #9: Keep "Hang Up" button on dialer
**Checklist**
 - [X] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [X]  I have read the FAQ and my problem isn't listed.
 - [X]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [X]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

I opened this same issue in the original repo before reading about the sale.

I recently installed Dialer on my grandmother's phone. Her one frustration occurs when trying to hang up a call after using the dial pad. She checks her voicemail by calling a number, and needs to open the dial pad to interact with the voicemail. When done, she looks on screen but does not see the hang up button, and does not know where to find it, which means she goes back to the home screen and gets stuck with a call running in the background.

I compared to the stock Graphene OS dialer, which maintains the hang up button in the dialpad. I believe the Google dialer must do this as well.

I am guessing that Simple Dialer hides the call button to keep compatibility with smaller screens, and to make it easier to dial with one hand. That said, would there be interest in a PR that addresses this?

I see two potential methods, either an adaptive behavior where the dialpad hides or shows the hang up button depending on screen size, or a toggle in options for "Show hang-up button on dialpad". If a PR would be welcome, which would be better?

### PR DESCRIPTION
**Pull request by Aga-C**
Closes #9

https://github.com/FossifyOrg/Phone/assets/85929121/2d3bc1b6-2e85-4286-b2ad-638d8517a847

### CODE REVIEW

**Comment by naveensingh** [comment]
@Aga-C The animation doesn't look okay but I don't have any ideas at the moment. I'll think about a better way to do it or you can try again if you want :)

**Comment by Aga-C** [comment]
What exactly could be done better?

**Comment by inson1** [comment]
I think it looks good. Even if there could be better way, this is better than nothing, so If some idea doesnt come, just merge it before next release, please

@Aga-C But what about bigger space between, the button and dialpad? just little bit?

**Comment by Aga-C** [comment]
@inson1 It's the same margin as in dialpad (the one before calling).

**Comment by inson1** [comment]
ok (that could be bigger but that isnt part of this PR)

**Comment by naveensingh** [comment]
Based on your recording, during the dialpad animation, the hangup button is below the semi-transparent dialpad and that looks like a glitch instead of an animation.

Check [this](https://www.apkmirror.com/apk/google-inc/google-phone/google-phone-7-0-140861421-nonnexus-release/google-phone-7-0-140861421-nonnexus-android-apk-download/download/?key=ec1ab43c4dce93bceab095c700bb686c49a41ab3) old Google Phone APK for inspiration.

Without redesigning the UI, we can do one of these:
 - Elevate the hangup button such that the dialpad appears behind it but in front of the other call UI buttons. In this case, the hangup button should always have some `android:elevation` set.
 - Hide the hangup button using shrink animation as it is currently -> Show the dialpad -> Show the hangup button using scale animation.

In any case, we should increase the dialpad bottom padding slightly so there's more padding between the hangup button and the 0 button on the dialpad.

**Comment by naveensingh** [comment]
> Even if there could be better way, this is better than nothing, so If some idea doesnt come, just merge it before next release

Something is always better than nothing, I absolutely agree with that. But in general and regarding any current or future contributions, I'll never merge a PR if I think the problem could have been solved in a better way. That is to enforce quality contributions and for my own peace of mind :)

**Comment by Aga-C** [comment]
I've added some margin to the bottom of the dialpad and went with the first option of changing the animation (added `elevation`).

**Comment by naveensingh** [comment]
Just made some UI changes to enable the dialpad elevation, thanks :+1:

**Pull request merged**
